version: '3.9'
networks:
  localwebnw:
    external: false
volumes:
  postgresdb:
  datavol:
services:
  dbserver:
    build: ./postgres/.
    container_name: 'dbserver'
    networks:
      - localwebnw
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgresdb
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always
  webserver:
    build: ./nginx/.
    container_name: 'webserver'
    networks:
      - localwebnw
    ports:
      - "80:80"
    volumes:
      - datavol:/datavol
    environment:
      - POSTGRES_SERVER=dbserver
      - POSTGRES_PORT=5432
      - POSTGRES_DB=settings_nginx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always
  webadmin:
    build: ./webadmin/.
    container_name: 'webadmin'
    networks:
      - localwebnw
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_SERVER=dbserver
      - POSTGRES_PORT=5432
      - POSTGRES_DB=settings_nginx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always
